### DISCUSSION TITLE
Problem with ESPHome 2024.10

### DISCUSSION THREAD

**Discussion by jasonxcool** [syssi/esphome-jbd-bms#106] [Q&A] [answered]
Hello, I have a problem compiling on ESPHome 2024.10, can you possibly help me?
I have "JBD UP16S015" BMS
The error only occurs with ESPHome 2024.10, before that it always worked.
I have also already done "clean build files".
The YAML has not been changed before.

```
substitutions:
  name: jbd-bms-uart
  device_description: "Monitor and control a Xiaoxiang Battery Management System (JBD-BMS) via UART"
  external_components_source: github://syssi/esphome-jbd-bms@main
  tx_pin: GPIO16
  rx_pin: GPIO17
  rx_timeout: 150ms

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jbd-bms"
    version: 2.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:
  level: DEBUG

ota:
  platform: esphome
  password: "**********"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Jbd-Bms-Uart Fallback Hotspot"
    password: "***********"

web_server:
  port: 80
  
captive_portal:

external_components:
  - source: ${external_components_source}
    refresh: 0s

api:
  encryption:
    key:  "*******************"

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

jbd_bms:
  - id: bms0
    update_interval: 15s
    rx_timeout: ${rx_timeout}

binary_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    online_status:
      name: "${name} online status"

sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    battery_strings:
      name: "${name} battery strings"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    state_of_charge:
      name: "${name} state of charge"
    nominal_capacity:
      name: "${name} nominal capacity"
    charging_cycles:
      name: "${name} charging cycles"
    capacity_remaining:
      name: "${name} capacity remaining"
    battery_cycle_capacity:
      name: "${name} battery cycle capacity"
    total_voltage:
      name: "${name} total voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    temperature_1:
      name: "${name} temperature 1"
    temperature_2:
      name: "${name} temperature 2"
    temperature_3:
      name: "${name} temperature 3"
    temperature_4:
      name: "${name} temperature 4"
    temperature_5:
      name: "${name} temperature 5"
    temperature_6:
      name: "${name} temperature 6"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    operation_status_bitmask:
      name: "${name} operation status bitmask"
    errors_bitmask:
      name: "${name} errors bitmask"
    balancer_status_bitmask:
      name: "${name} balancer status bitmask"
    software_version:
      name: "${name} software version"

text_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    errors:
      name: "${name} errors"
    operation_status:
      name: "${name} operation status"
    device_model:
      name: "${name} device model"

switch:
  - platform: jbd_bms
    jbd_bms_id: bms0
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging" 
```

I get this message when compiling!

```
 INFO ESPHome 2024.10.2
 INFO Reading configuration /config/esphome/jbd-bms-uart.yaml...
 INFO Updating https://github.com/syssi/esphome-jbd-bms.git@main
 INFO Generating C++ source...
 INFO Compiling app...
 Processing jbd-bms-uart (board: wemos_d1_mini32; framework: espidf; platform: platformio/espressif32@5.4.0)
 --------------------------------------------------------------------------------
 MissingPackageManifestError: Could not find one of 'package.json' manifest files in the package

```
