### DISCUSSION TITLE
Beginner needs help

### DISCUSSION THREAD

**Discussion by jdrescher2006** [syssi/esphome-jbd-bms#58] [Q&A] [answered]
Hi everybody,
thank you very much for this nice project!

I have a ESP8266 (NodeMCU V3) and via the web installer (ESP Web Tools) I managed to get ESPhome installed. The ESP now has a static IP in my network and is showing the ESPHome start page.

I don't use HomeAssistant, so I need to use the command line with python.
Following the guide in the readme, the compiling looks quite successful. But in the end I get: "ERROR Error resolving IP address of jbd-bms-uart.local. Is it connected to WiFi?".

Also I noticed, that the model in "esp32-example.yaml" does not fit to my board: "board: wemos_d1_mini32".

How can I fix these problems?

**Comment by syssi** [comment, marked as answer]
If you have a ESP8266 you have to use the dedicated example: https://github.com/syssi/esphome-jbd-bms/blob/main/esp8266-example.yaml

If you cannot access the ESPHome node using the hostname (because it has changed probably) you can use the IP address:

```
esphome run esp8266-example.yaml --device 192.168.1.123
```

**Comment by jdrescher2006** [comment]
Thanks for that, looks better now, upload is now successful.
However there is one problem left: "ERROR No remote or local logging method configured (api/mqtt/logger)"

Also now, there is no website. Do I need to use a port?

By the way, the board is set to "board: d1_mini", but I have a NodeMCU V3, could that be a problem?

**Reply by syssi** [reply]
This sounds like you have removed some sections `api`, `mqtt`, `logger`. Please use

```
logger:
  level: DEBUG

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client
```

or

```
logger:
  level: DEBUG

api:
  reboot_timeout: 0s
```

If you want a web interface you have to add the `web_server` component:

```
web_server:
  local: false
```
