### DISCUSSION TITLE
A beginner's question in Home Assistant

### DISCUSSION THREAD

**Discussion by Rafalll111** [syssi/esphome-jbd-bms#61] [Q&A]
How to increase the frequency of measurement reporting. now I have reports in Home Assistant every 5 minutes.

**Comment by syssi** [comment]
Do you use a BLE or UART connection? Per default the `update_interval` should be around 2 seconds.

**Reply by syssi** [reply]
```
jbd_bms:
  - id: bms0
    update_interval: 2s
    rx_timeout: ${rx_timeout}
```

```
jbd_bms_ble:
  - id: bms0
    update_interval: 2s
```
