### DISCUSSION TITLE
is it possible to connect 2 UART ports on esp32?

### DISCUSSION THREAD

**Discussion by shurik05** [syssi/esphome-jbd-bms#71] [Q&A] [answered]
I seen an example for esphome-jk-bms to utilize 2 uart ports on esp32 is that possible with esphome-jbd-bms as I do not see any examples. I tried the following but get the following error message. 
"Too many candidates found for 'uart_id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'."

```
substitutions:
  name: jbd-bms-uart
  device_description: "Monitor and control a Xiaoxiang Battery Management System (JBD-BMS) via UART"
  external_components_source: github://smaksimowicz/esphome-jbd-bms@main #external_components_source: github://syssi/esphome-jbd-bms@main
  tx_pin_uart_0: GPIO04
  rx_pin_uart_0: GPIO05
  tx_pin_uart_1: GPIO14
  rx_pin_uart_1: GPIO15
  rx_timeout: 150ms

external_components:
  - source: ${external_components_source}
    refresh: 0s

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin_uart_0}
    rx_pin: ${rx_pin_uart_0}
  - id: uart_1
    baud_rate: 9600
    tx_pin: ${tx_pin_uart_1}
    rx_pin: ${rx_pin_uart_1}
```
