### DISCUSSION TITLE
Multiple BLE BMS causes a lot of WiFi loss and possibly esp32 restarts

### DISCUSSION THREAD

**Discussion by jdscavo** [syssi/esphome-jbd-bms#91] [Q&A]
Trying to monitor two battery BMS. For the most part this works great. A great solutoon and many thanks. Problem is this configuration keeps experiencing loss of wifi and I think even some restarts. I can not provide logs for are the restarts, since I can't connect to get logs. I can see the device drops off the network by doing ping tests. When things are working, the esp32 has a strong WiFi connection and the BLE connections seem to be solid when the connection are working. I've tried two different versions esp32 board devices with same result. Could someone look at the yaml I'm using and see if there is something I've messed up? Sorry i'm not figuring out how to paste the yaml as code. Thanks in advance.

```
`# Multi battery monitoring for Chins jbd bms bluetooth batteries. Adapted from multi device example from below github source.
substitutions:
  name: miniesp32
  friendly_name: miniesp32
  bms0: "100Ah bms0"
  bms1: "290Ah bms1"
  device_description: "Monitor and control dual Chins Battery Management System (JBD-BMS) via BLE"
  external_components_source: github://syssi/esphome-jbd-bms@main
# 100Ah LiPo battery
  bms0_mac_address: A5:C2:37:13:B3:0C
# 290 Ah LiPo battery
  bms1_mac_address: A5:C2:37:27:D0:BA


esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jbd-bms"
    version: 2.0.0

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxx"

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: "xxxxxxxx"
  password: "xxxxxxx"

# Turn on a web server
web_server:

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("xiaoxiang", 0) == 0) {
            ESP_LOGI("ble_adv", "New JBD-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1

jbd_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 5s
  - id: bms1
    ble_client_id: client1
    update_interval: 5s

button:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    retrieve_hardware_version:
      name: "${name} retrieve hardware version"
# Make a reset button
  - platform: restart
    name: "miniesp32 Restart"

binary_sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"
    online_status:
      name: "${bms0} online status"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    balancing:
      name: "${bms1} balancing"
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"
    online_status:
      name: "${bms1} online status"

sensor:
# WiFi signal monitor- nothing to do with jbd bt
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
# bms sensors
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    battery_strings:
      name: "${bms0} battery strings"
    current:
      name: "${bms0} current"
    power:
      name: "${bms0} power"
    charging_power:
      name: "${bms0} charging power"
    discharging_power:
      name: "${bms0} discharging power"
    state_of_charge:
      name: "${bms0} state of charge"
    nominal_capacity:
      name: "${bms0} nominal capacity"
    charging_cycles:
      name: "${bms0} charging cycles"
    capacity_remaining:
      name: "${bms0} capacity remaining"
    battery_cycle_capacity:
      name: "${bms0} battery cycle capacity"
    total_voltage:
      name: "${bms0} total voltage"
    average_cell_voltage:
      name: "${bms0} average cell voltage"
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    min_cell_voltage:
      name: "${bms0} min cell voltage"
    max_cell_voltage:
      name: "${bms0} max cell voltage"
    min_voltage_cell:
      name: "${bms0} min voltage cell"
    max_voltage_cell:
      name: "${bms0} max voltage cell"
    temperature_1:
      name: "${bms0} temperature 1"
    cell_voltage_1:
      name: "${bms0} cell voltage 1"
    cell_voltage_2:
      name: "${bms0} cell voltage 2"
    cell_voltage_3:
      name: "${bms0} cell voltage 3"
    cell_voltage_4:
      name: "${bms0} cell voltage 4"
    operation_status_bitmask:
      name: "${bms0} operation status bitmask"
    errors_bitmask:
      name: "${bms0} errors bitmask"
    balancer_status_bitmask:
      name: "${bms0} balancer status bitmask"
    software_version:
      name: "${bms0} software version"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    battery_strings:
      name: "${bms1} battery strings"
    current:
      name: "${bms1} current"
    power:
      name: "${bms1} power"
    charging_power:
      name: "${bms1} charging power"
    discharging_power:
      name: "${bms1} discharging power"
    state_of_charge:
      name: "${bms1} state of charge"
    nominal_capacity:
      name: "${bms1} nominal capacity"
    charging_cycles:
      name: "${bms1} charging cycles"
    capacity_remaining:
      name: "${bms1} capacity remaining"
    battery_cycle_capacity:
      name: "${bms1} battery cycle capacity"
    total_voltage:
      name: "${bms1} total voltage"
    average_cell_voltage:
      name: "${bms1} average cell voltage"
    delta_cell_voltage:
      name: "${bms1} delta cell voltage"
    min_cell_voltage:
      name: "${bms1} min cell voltage"
    max_cell_voltage:
      name: "${bms1} max cell voltage"
    min_voltage_cell:
      name: "${bms1} min voltage cell"
    max_voltage_cell:
      name: "${bms1} max voltage cell"
    temperature_1:
      name: "${bms1} temperature 1"
    cell_voltage_1:
      name: "${bms1} cell voltage 1"
    cell_voltage_2:
      name: "${bms1} cell voltage 2"
    cell_voltage_3:
      name: "${bms1} cell voltage 3"
    cell_voltage_4:
      name: "${bms1} cell voltage 4"
    operation_status_bitmask:
      name: "${bms1} operation status bitmask"
    errors_bitmask:
      name: "${bms1} errors bitmask"
    balancer_status_bitmask:
      name: "${bms1} balancer status bitmask"
    software_version:
      name: "${bms1} software version"

text_sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    errors:
      name: "${bms0} errors"
    operation_status:
      name: "${bms0} operation status"
    device_model:
      name: "${bms0} device model"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    errors:
      name: "${bms1} errors"
    operation_status:
      name: "${bms1} operation status"
    device_model:
      name: "${bms1} device model"

switch:
  - platform: ble_client
    ble_client_id: client0
    name: "${bms0} enable bluetooth connection"

  - platform: ble_client
    ble_client_id: client1
    name: "${bms1} enable bluetooth connection"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"`
```

**Comment by syssi** [comment]
Please try to remove stuff which needs a lot of resources:

1. Remove the `web server` component 
2. Decrease the log level to `INFO`
3. Remove the complete `on_ble_advertise` section from the BLE tracker. It's just a helper to identify the MAC address of your devices
4. Use the framework.typ `esp-idf` instead of `Arduino`

**Reply by syssi** [reply]
Last but not least if you have the option avoid WiFi and use a WT32-ETH01 or some other dev board equipped with a supported Ethernet module.

**Reply by jdscavo** [reply]
Just made the recommended changes to the configuration. Unfortunately I can not use an ethernet connection for this application. So far the thing is rock solid reading the two batteries and using WiFi to connect to HA! Only warnings I see occasionally now are:

**[17:20:19][W][component:237]: Component esp32_ble took a long time for an operation (55 ms).
[17:20:19][W][component:238]: Components should block for at most 30 ms.**
[17:20:19][I][jbd_bms_ble:191]: Cell info frame (8 bytes) received
[17:20:20][I][jbd_bms_ble:242]: Hardware info frame (34 bytes) received

I'm such a noob at the esp32 devices. So much more fun than the ardruno, and amazed at what these <$5 devices can do. Still trying to figure out the correct/optimized basic esp32 declaratives that esphome provisions on initial install that just to make the things run. Your help is greatly appreciated.

Thank you for the pointers and an awesome solution.

**Reply by jdscavo** [reply]
The changes seemed to help, but now get a very different error that repeats over and over after about 20 minutes after the esp32 starts up;
`BT_APPL: bta_gattc_enqueue(), the gattc command queue is full`

**Reply by syssi** [reply]
Could you try to reduce the update interval of both instances:

```
jbd_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 10s
  - id: bms1
    ble_client_id: client1
    update_interval: 10s
```

Could you tell me the log level of the message? It is a warning or an error? This message is new to me.

**Reply by syssi** [reply]
Which ESPHome version do you use? Please provide the explicit version number.

**Reply by jdscavo** [reply]
Using ESPHome 2024.7.3. I have log level set to INFO as suggested. Messages are errors and not warnings. The entities become unavailable when the errors start. I think the BMS model trying to read data from is DP04S007 v1.7. 

Messing with update_interval:  seems to have some correlation with the errors. Increasing update_interval: from five to eight seemed to slow the error messages. Raising update_interval: 10 as suggested the device worked flawlessly for about 12 hours. Then I checked it again to update this message and the errors below were back. Also included is currently running yaml snippet. 

INFO Successful handshake with batt-mon @ 10.144.28.13 in 0.123s
[00:07:37][I][app:100]: ESPHome version 2024.7.3 compiled on Aug  7 2024, 01:35:19
[00:07:37][I][app:102]: Project syssi.esphome-jbd-bms version 2.0.0
[00:07:42][I][esp-idf:000][BTU_TASK]: E (13367278) BT_APPL: bta_gattc_enqueue(), the gattc command queue is full.

[00:07:43][I][esp-idf:000][BTU_TASK]: E (13368077) BT_APPL: bta_gattc_enqueue(), the gattc command queue is full.

[00:07:52][I][esp-idf:000][BTU_TASK]: E (13377272) BT_APPL: bta_gattc_enqueue(), the gattc command queue is full.

[00:07:53][I][esp-idf:000][BTU_TASK]: E (13378078) BT_APPL: bta_gattc_enqueue(), the gattc command queue is full.

```substitutions:
  name: batt-mon
  friendly_name: batt-mon
  bms0: "100Ah bms0"
  bms1: "290Ah bms1"
  device_description: "Monitor and control dual Chins Battery Management System (JBD-BMS) via BLE"
  external_components_source: github://syssi/esphome-jbd-bms@main
# 100Ah LiPo battery
  bms0_mac_address: A5:C2:37:13:B3:0C
# 290 Ah LiPo battery
  bms1_mac_address: A5:C2:37:27:D0:BA


esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jbd-bms"
    version: 2.0.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxx"

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: "xxxxxxxx"
  password: "xxxxxxxxx"

  # Optional manual IP
  manual_ip:
    static_ip: 10.144.28.13
    gateway: 10.144.28.1
    subnet: 255.255.255.0

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1

jbd_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 10s
  - id: bms1
    ble_client_id: client1
    update_interval: 10s

button:
... etc...
```

**Reply by syssi** [reply]
Does it happen too if you monitor a single BMS?

**Reply by jdscavo** [reply]
Excellent question. When I first tried this code, I built it for a single BMS. This was also the second project I tried on esphome... So I "think" it was working. Data from the BMS was updating an entity. As far as errors or how long it was working I don't know. Once i saw it was working, I jumped into the multi reader.  Later this afternoon, I will build another esp32 with the yaml for a single monitor and post an update.

**Reply by jdscavo** [reply]
Last night was able to provision the esp32 to read just one bms. It worked fine for a while, then started getting the same error. I used the same esp32 board that the multi reader was set up on. I must have something misconfigured. Maybe the board type? I've been using esphome to do the initial install on the esp32 boards. It chooses esp32: board: esp32dev. The imprint on the board says esp-wroom-32. So new at using these, I don't know if there is any correlation. This is the result error that continually repeats:
```
[11:25:28][I][app:100]: ESPHome version 2024.7.3 compiled on Aug  9 2024, 02:27:52
[11:25:28][I][app:102]: Project syssi.esphome-jbd-bms version 1.5.0
[11:25:33][I][esp-idf:000][BTU_TASK]: E (32118526) BT_APPL: bta_gattc_enqueue(), the gattc command queue is full.
```
Here is the yaml snippet that was deployed:
```
substitutions:
  name: batt-mon
  friendly_name: batt-mon
  bms0: "100Ah bms0"
  device_description: "Example - Monitor and control a Xiaoxiang Battery Management System (JBD-BMS) via BLE"
  external_components_source: github://syssi/esphome-jbd-bms@main
# 100Ah LiPo battery bms0
  mac_address: A5:C2:37:13:B3:0C

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jbd-bms"
    version: 1.5.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxx"

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: "xxxxx"
  password: "xxxxx"
  # Optional manual IP
  manual_ip:
    static_ip: 10.144.28.13
    gateway: 10.144.28.1
    subnet: 255.255.255.0

ble_client:
  - id: client0
    mac_address: ${mac_address}

jbd_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 10s

button:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    retrieve_hardware_version:
      name: "${bms0} retrieve hardware version"
# Make a reset button
  - platform: restart
    name: "Restart batt-mon"

binary_sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"
    online_status:
      name: "${bms0} online status"

sensor:
# WiFi signal monitor- nothing to do with jbd bt
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    battery_strings:
      name: "${bms0} battery strings"
    current:
      name: "${bms0} current"
...etc...
```

**Comment by jdscavo** [comment]
After hours of testing, I'm sure that two of the three esp32 boards I used are the problem. Two of the USB-C esp32dev boards WiFi/Bluetooth signal performance is significantly degraded compared to similar USB-Mini esp32dev boards. Signal strengths could have contributed to the errors, but even with the USB-C devices, signals still displayed under -40DB and usually considered very good. All the devices were created using documented esphome procedure. After confirming the board was working, I used the esphome installed .yaml to modify the multi BMS .yaml code in this project. On a side note, I found that setting a static IP really helped with using ota to flash the devices. Seems that mDNS on my router is problematic, so having the static IP helps eleviate some network issues.

I am very happy to report that finding the right esp32 hardware works great with this project. After testing so many setting senarios and hardware combinations, the settings below and the one esp32 device it is installed on has been working flawlessly for the better part of a day. 

```
# Multi battery monitroing for Chins jbd bms bluetooth batteries. Adapted from multi device example from below github source.
substitutions:
  name: bms-master
  friendly_name: bms-master
  bms0: "100Ah bms0"
  bms1: "290Ah bms1"
  device_description: "Monitor and control dual Chins Battery Management System (JBD-BMS) via BLE"
  external_components_source: github://syssi/esphome-jbd-bms@main
# 100Ah LiPo battery
  bms0_mac_address: A5:C2:37:13:B3:0C
# 290 Ah LiPo battery
  bms1_mac_address: A5:C2:37:27:D0:BA


esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jbd-bms"
    version: 2.0.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    
# Enable logging
logger:
  level: INFO

external_components:
  - source: ${external_components_source}
    refresh: 0s

# Enable Home Assistant API, ota and WiFi
# USB Mini esp32
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  # mac CC:DB:A7:30:0D:48
  manual_ip:
    static_ip: 10.144.28.14
    gateway: 10.144.28.1
    subnet: 255.255.255.0

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1

jbd_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 10s
  - id: bms1
    ble_client_id: client1
    update_interval: 10s

button:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    retrieve_hardware_version:
      name: "${name} retrieve hardware version"
# Make a reset button
  - platform: restart
    name: "Restart batt-mon"

binary_sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"
    online_status:
      name: "${bms0} online status"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    balancing:
      name: "${bms1} balancing"
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"
    online_status:
      name: "${bms1} online status"

sensor:
# WiFi signal monitor- nothing to do with jbd bt
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    type: seconds
    name: Uptime Sensor
# bms sensors
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    battery_strings:
      name: "${bms0} battery strings"
    current:
      name: "${bms0} current"
    power:
      name: "${bms0} power"
    charging_power:
      name: "${bms0} charging power"
    discharging_power:
      name: "${bms0} discharging power"
    state_of_charge:
      name: "${bms0} state of charge"
    nominal_capacity:
      name: "${bms0} nominal capacity"
    charging_cycles:
      name: "${bms0} charging cycles"
    capacity_remaining:
      name: "${bms0} capacity remaining"
    battery_cycle_capacity:
      name: "${bms0} battery cycle capacity"
    total_voltage:
      name: "${bms0} total voltage"
    average_cell_voltage:
      name: "${bms0} average cell voltage"
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    min_cell_voltage:
      name: "${bms0} min cell voltage"
    max_cell_voltage:
      name: "${bms0} max cell voltage"
    min_voltage_cell:
      name: "${bms0} min voltage cell"
    max_voltage_cell:
      name: "${bms0} max voltage cell"
    temperature_1:
      name: "${bms0} temperature 1"
    cell_voltage_1:
      name: "${bms0} cell voltage 1"
    cell_voltage_2:
      name: "${bms0} cell voltage 2"
    cell_voltage_3:
      name: "${bms0} cell voltage 3"
    cell_voltage_4:
      name: "${bms0} cell voltage 4"
    operation_status_bitmask:
      name: "${bms0} operation status bitmask"
    errors_bitmask:
      name: "${bms0} errors bitmask"
    balancer_status_bitmask:
      name: "${bms0} balancer status bitmask"
    software_version:
      name: "${bms0} software version"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    battery_strings:
      name: "${bms1} battery strings"
    current:
      name: "${bms1} current"
    power:
      name: "${bms1} power"
    charging_power:
      name: "${bms1} charging power"
    discharging_power:
      name: "${bms1} discharging power"
    state_of_charge:
      name: "${bms1} state of charge"
    nominal_capacity:
      name: "${bms1} nominal capacity"
    charging_cycles:
      name: "${bms1} charging cycles"
    capacity_remaining:
      name: "${bms1} capacity remaining"
    battery_cycle_capacity:
      name: "${bms1} battery cycle capacity"
    total_voltage:
      name: "${bms1} total voltage"
    average_cell_voltage:
      name: "${bms1} average cell voltage"
    delta_cell_voltage:
      name: "${bms1} delta cell voltage"
    min_cell_voltage:
      name: "${bms1} min cell voltage"
    max_cell_voltage:
      name: "${bms1} max cell voltage"
    min_voltage_cell:
      name: "${bms1} min voltage cell"
    max_voltage_cell:
      name: "${bms1} max voltage cell"
    temperature_1:
      name: "${bms1} temperature 1"
    cell_voltage_1:
      name: "${bms1} cell voltage 1"
    cell_voltage_2:
      name: "${bms1} cell voltage 2"
    cell_voltage_3:
      name: "${bms1} cell voltage 3"
    cell_voltage_4:
      name: "${bms1} cell voltage 4"
    operation_status_bitmask:
      name: "${bms1} operation status bitmask"
    errors_bitmask:
      name: "${bms1} errors bitmask"
    balancer_status_bitmask:
      name: "${bms1} balancer status bitmask"
    software_version:
      name: "${bms1} software version"

text_sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    errors:
      name: "${bms0} errors"
    operation_status:
      name: "${bms0} operation status"
    device_model:
      name: "${bms0} device model"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    errors:
      name: "${bms1} errors"
    operation_status:
      name: "${bms1} operation status"
    device_model:
      name: "${bms1} device model"

switch:
  - platform: ble_client
    ble_client_id: client0
    name: "${bms0} enable bluetooth connection"

  - platform: ble_client
    ble_client_id: client1
    name: "${bms1} enable bluetooth connection"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"

# Safe mode restart
  - platform: safe_mode
    name: "batt-mon Restart (Safe Mode)"    
```
Thank you so much for the ideas to effectivly work through these issues. Now on to build the automations and dashboards for an ad-hoc engineered solar system.
