### DISCUSSION TITLE
Reusable BMS Package

### DISCUSSION THREAD

**Discussion by 20after4** [syssi/esphome-jbd-bms#99] [Show and tell]
I've built out the yaml for a reusable package that you can include multiple times for multiple BMS instances from a single esphome device.  I've only been able to get 3 bms instances to work on a single device due to limitations in the esp-idf bluetooth stack. 

Here's a usage example:

```yaml
packages:
  bms2: !include
    file: esphome-bms-monitor/bms.yaml
    vars:
      bms_id: bms2
      linked_bms: bms3
      bms_mac_address: "A4:C1:XX:XX:XX"
      update_interval: 20s
      sync: 1
  bms3: !include
    file: esphome-bms-monitor/bms.yaml
    vars:
      bms_id: bms3
      linked_bms: bms2
      bms_mac_address: "A4:C1:YY:YY:YY"
      update_interval: 20s
      sync: 1
```

The sync feature causes enable/disable controls to propagate so that you can enable them as a group.

The full component is at https://github.com/20after4/esphome-energy-monitor/blob/main/esphome-bms-monitor/bms.yaml

Hopefully someone might find this useful.
