### ISSUE TITLE
Build HA entity_id from id of the object

### ISSUE THREAD

**Issue by ThomasCr** [syssi/esphome-jbd-bms#100]
Hi,

today I started with this nice project and wanted to translate and rename some items for me. What I don't like, when the `entity_id` changes (this happens if I change the name attribute). So I defined for every "sensor/button/..." a own id. But at the end, I noticed, that those IDs was not used in HA.

(small example where I am)
```
sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    battery_strings:
      id: "jbd_bms0_battery_strings"
      name: "${bms0_name} Batteriestränge"
    current:
      id: "jbd_bms0_current"
      name: "${bms0_name} Stromstärke"
    power:
      id: "jbd_bms0_power"
      name: "${bms0_name} Leistung"
```

Can you generate the `entity_id` in your code? Or allow us to define this attribute?

When I try to define it, I get the message: 

> [entity_id] is an invalid option for [battery_strings]. Did you mean [mqtt_id]?

In your code are also all the other HA attributes defined.

So it should be not such a big problem to do (pseudo code):
```
if id defined:
  set  entity_id = sensor.$id
```
