### ISSUE TITLE
build on esp32 with framework arduino instead of esp-idf

### ISSUE THREAD

**Issue by b2un0** [syssi/esphome-jbd-bms#104]
hey there,

is it possible to build this with the 

```yaml
esp32:
  framework:
    type: arduino
```

i would like to build this on the same ESP32 where i'm using the [GPS Component](https://esphome.io/components/gps.html).
But this seems to be incompatible with the `esp-idf` framework.
see also here 
https://github.com/mikalhart/TinyGPSPlus/pull/69
