### ISSUE TITLE
calculate state of charge manually or better alternative?

### ISSUE THREAD

**Issue by b2un0** [syssi/esphome-jbd-bms#138]
hi there,

first of all thanks for your work. using your component now for over a year.

currently im struggling with an issue, that the "state_of_charge" sensor remains on 99%.

i have a Model DP04S007L4S100A with 100A 4 strings.

![Image](https://github.com/user-attachments/assets/54f8ceab-e6ff-43e4-8ce3-fd2dcec52a99)

![Image](https://github.com/user-attachments/assets/08b605f8-9376-42a6-9894-a7c00fcbb2b2)

![Image](https://github.com/user-attachments/assets/43f417ca-9a0d-459a-9767-52f100661ac2)

![Image](https://github.com/user-attachments/assets/35028f35-2296-40f4-885b-3bb064dcdfb8)

![Image](https://github.com/user-attachments/assets/0c3c0741-52b8-41fd-9091-b6cdc328eb8d)

i have some low power consumers, like the esp32 self, a "Truma CP Plus" for the Heater and an LTE Router.

if i calculate all 4 cells 
Cell 1: 3.316 V
Cell 2: 3.315 V
Cell 3: 3.317 V
Cell 4: 3.315 V

i got 13.263 V (also not matches the "total voltage" sensor)

for now, im using a template sensor like this

```yaml
sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    battery_strings:
      name: "JBD BMS battery strings"
      id: jdb_bms_battery strings
    current:
      name: "JBD BMS current"
      id: jdb_bms_current
    power:
      name: "JBD BMS power"
      id: jdb_bms_power
    charging_power:
      name: "JBD BMS charging power"
      id: jdb_bms_charging_power
    discharging_power:
      name: "JBD BMS discharging power"
      id: jdb_bms_discharging_power
    state_of_charge:
      name: "JBD BMS state of charge"
      id: jdb_bms_soc
    nominal_capacity:
      name: "JBD BMS nominal capacity"
      id: jdb_bms_nominal_capacity
  - platform: template
    name: "JBD BMS State of Charge (Voltage)"
    id: vince_jbd_bms_soc_voltage
    unit_of_measurement: "%"
    state_class: "measurement"
    device_class: "battery"
    update_interval: 10s
    lambda: |-
      float voltage = id(bms_total_voltage).state;
      if (voltage >= 14.4) { return 100; }
      else if (voltage >= 14.0) { return 99; }
      else if (voltage >= 13.8) { return 98; }
      else if (voltage >= 13.6) { return 97; }
      else if (voltage >= 13.55) { return 96; }
      else if (voltage >= 13.5) { return 95; }
      else if (voltage >= 13.45) { return 90; }
      else if (voltage >= 13.4) { return 85; }
      else if (voltage >= 13.35) { return 80; }
      else if (voltage >= 13.3) { return 75; }
      else if (voltage >= 13.25) { return 70; }
      else if (voltage >= 13.2) { return 65; }
      else if (voltage >= 13.15) { return 60; }
      else if (voltage >= 13.1) { return 55; }
      else if (voltage >= 13.05) { return 50; }
      else if (voltage >= 13.0) { return 45; }
      else if (voltage >= 12.9) { return 40; }
      else if (voltage >= 12.8) { return 30; }
      else if (voltage >= 12.7) { return 25; }
      else if (voltage >= 12.6) { return 20; }
      else if (voltage >= 12.0) { return 15; } // Hier fällt die Spannung dann schnell
      else if (voltage >= 11.5) { return 10; }
      else if (voltage >= 11.0) { return 5; }
      else { return 0; }
```

are there better solutions for this?

Have I missed something?
