### ISSUE TITLE
ERROR Circular dependency detected!

### ISSUE THREAD

**Issue by Sleeper85** [syssi/esphome-jbd-bms#141]
Hi Syssi,

Compilation results in a circular dependency error when starting from the example file `esp32-example.yaml` and adding a template sensor returning the value of `name: "${name} battery cycle capacity"`.

Tested with esphome `2024.11.3` and `2025.5.2`.

The example code has been simplified as much as possible.

[esp32-example-jbd.yaml.txt](https://github.com/user-attachments/files/20750673/esp32-example-jbd.yaml.txt)

```YAML
sensor:

  - platform: jbd_bms
    jbd_bms_id: bms0
    battery_cycle_capacity:
      name: "${name} battery cycle capacity"
      id: cycle_capacity_raw

  - platform: template
    name: "${name} total charging cycle capacity"
    update_interval: 5s
    unit_of_measurement: Ah
    state_class: total
    icon: mdi:car-battery
    accuracy_decimals: 0
    lambda: return id(cycle_capacity_raw).state;
```

Thanks for your help.
