### ISSUE TITLE
JBD-AP21S002 no BLE connection

### ISSUE THREAD

**Issue by Zahnpasta83** [syssi/esphome-jbd-bms#44]
Hello,

i tried to get a connection with JBD-AP21S002 BMS but i am unable. Thought there wouldn't be a big difference to the JBD-AP21S001. Is there a possibility to get it run on the S002 Version?

<img width="930" alt="Bildschirm­foto 2023-06-27 um 16 59 10" src="https://github.com/syssi/esphome-jbd-bms/assets/122221616/82a1c54d-7d7c-4b6f-8675-11b2d3da9f2d">
<img width="1237" alt="Bildschirm­foto 2023-06-27 um 16 59 40" src="https://github.com/syssi/esphome-jbd-bms/assets/122221616/787b4dc2-ebef-4d24-91a2-04a450177cfb">

**Comment by syssi** [comment]
Did you update the `mac_address` to the one of your device? Is the ESP32 able to establish a BLE client connection to the BMS?

**Comment by syssi** [comment]
Please increase the debug level of some components using this snippet:

```
logger:
  level: VERY_VERBOSE
  logs:
    esp32_ble_tracker: VERY_VERBOSE
    jbd_bms_ble: VERY_VERBOSE
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
```

Flash your ESP another time and provide a complete log. There should be some lines of the `esp32_ble_tracker' which reports all visible devices and some log lines of the `ble_client` component which tries to establish a connection to the BMS. If the connection gets established a component should report which service UUIDs and characteristics are available. If your BMS doesn't like the implementation you will see a disconnect and "Not connected" warnings later on.
